### ISSUE TITLE
Improvement: Need auto scalling editor

### ISSUE THREAD

**Issue by kingRayhan** [shoaibsharif/snippet_frontend#3]

**Comment by shoaibsharif** [comment]
can you please be more specific?

**Comment by kingRayhan** [comment]
See this

https://medium.com/@adamorlowskipoland/vue-auto-resize-textarea-3-different-approaches-8bbda5d074ce

**Comment by shoaibsharif** [comment]
should fix with f6c11c4a98dcedcd384721b59a8972b96331b88c
